Add MAXMIND_LICENSE_KEY env var in order to download GeoLite2 databases Move GeoLite2 databases to /data/geoip folder Fix remote ip for MM_ADDR and MMDB_ADDR fastcgi params

diff --git a/assets/usr/local/bin/update_geoip b/assets/usr/local/bin/update_geoip
--- a/assets/usr/local/bin/update_geoip
+++ b/assets/usr/local/bin/update_geoip
@@ -1,24 +1,41 @@
 #!/bin/sh
 
+if [ -z "$MAXMIND_LICENSE_KEY" ]; then
+  >&2 echo "ERROR: MAXMIND_LICENSE_KEY must be defined in order to download GeoLite2 databases"
+  exit 1
+fi
+
 mkdir -p /tmp/geoip
 cd /tmp/geoip/
 
 echo "Updating GeoLite2-City..."
-wget -q http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
-tar -xzf GeoLite2-City.tar.gz --strip-components=1
-mv -f GeoLite2-City.mmdb /etc/nginx/geoip/
-echo $(date -r /etc/nginx/geoip/GeoLite2-City.mmdb)
+dlErrorMsg=$(curl --location --fail --silent --show-error --output "GeoLite2-City.tar.gz" "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&suffix=tar.gz&license_key=${MAXMIND_LICENSE_KEY}" 2>&1)
+if [ -n "${dlErrorMsg}" ]; then
+  echo "ERROR: ${dlErrorMsg}"
+else
+  tar -xzf GeoLite2-City.tar.gz --strip-components=1
+  mv -f GeoLite2-City.mmdb /data/geoip/
+  echo $(date -r /data/geoip/GeoLite2-City.mmdb)
+fi
 
 echo "Updating GeoLite2-Country..."
-wget -q http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz
-tar -xzf GeoLite2-Country.tar.gz --strip-components=1
-mv -f GeoLite2-Country.mmdb /etc/nginx/geoip/
-echo $(date -r /etc/nginx/geoip/GeoLite2-Country.mmdb)
+dlErrorMsg=$(curl --location --fail --silent --show-error --output "GeoLite2-Country.tar.gz" "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&suffix=tar.gz&license_key=${MAXMIND_LICENSE_KEY}" 2>&1)
+if [ -n "${dlErrorMsg}" ]; then
+  echo "ERROR: ${dlErrorMsg}"
+else
+  tar -xzf GeoLite2-Country.tar.gz --strip-components=1
+  mv -f GeoLite2-Country.mmdb /data/geoip/
+  echo $(date -r /data/geoip/GeoLite2-Country.mmdb)
+fi
 
 echo "Updating GeoLite2-ASN..."
-wget -q http://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN.tar.gz
-tar -xzf GeoLite2-ASN.tar.gz --strip-components=1
-mv -f GeoLite2-ASN.mmdb /etc/nginx/geoip/
-echo $(date -r /etc/nginx/geoip/GeoLite2-ASN.mmdb)
+dlErrorMsg=$(curl --location --fail --silent --show-error --output "GeoLite2-ASN.tar.gz" "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&suffix=tar.gz&license_key=${MAXMIND_LICENSE_KEY}" 2>&1)
+if [ -n "${dlErrorMsg}" ]; then
+  echo "ERROR: ${dlErrorMsg}"
+else
+  tar -xzf GeoLite2-ASN.tar.gz --strip-components=1
+  mv -f GeoLite2-ASN.mmdb /data/geoip/
+  echo $(date -r /data/geoip/GeoLite2-ASN.mmdb)
+fi
 
 rm -rf /tmp/geoip/*
